### ISSUE TITLE
ModuleNotFoundError: No module named 'apache_beam' for wikipedia datasets 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/datasets#1977]
Hi
I am trying to run run_mlm.py code [1] of huggingface with following "wikipedia"/ "20200501.aa"  dataset:

`python run_mlm.py     --model_name_or_path bert-base-multilingual-cased --dataset_name wikipedia     --dataset_config_name 20200501.aa     --do_train     --do_eval     --output_dir /tmp/test-mlm --max_seq_length 256
`

I am getting this error, but as per documentation, huggingface dataset provide processed version of this dataset and users can load it without requiring setup extra settings. could you help me please to load this dataset? 
Do you think I can run run_ml.py with this dataset? I need to contact multiple of these datasets in different languages and train the model. Does the library bring these large datasets all in memory? Since I need to use multiple of them, is there a way I subsample them so I can train a model on multiple of them?

I really appreciate your help.
@lhoestq 

thanks.

[1] https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py

error I get: 

```
>>> import datasets 
>>> datasets.load_dataset("wikipedia", "20200501.aa")
Downloading and preparing dataset wikipedia/20200501.aa (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /dara/temp/cache_home_2/datasets/wikipedia/20200501.aa/1.0.0/4021357e28509391eab2f8300d9b689e7e8f3a877ebb3d354b01577d497ebc63...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dara/temp/libs/anaconda3/envs/codes/lib/python3.7/site-packages/datasets-1.3.0-py3.7.egg/datasets/load.py", line 746, in load_dataset
    use_auth_token=use_auth_token,
  File "/dara/temp/libs/anaconda3/envs/codes/lib/python3.7/site-packages/datasets-1.3.0-py3.7.egg/datasets/builder.py", line 573, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/dara/temp/libs/anaconda3/envs/codes/lib/python3.7/site-packages/datasets-1.3.0-py3.7.egg/datasets/builder.py", line 1099, in _download_and_prepare
    import apache_beam as beam
ModuleNotFoundError: No module named 'apache_beam'

```

**Comment by dorost1234** [comment]
I sometimes also get this error:

  File "/dara/libs/anaconda3/envs/code/lib/python3.7/site-packages/datasets-1.3.0-py3.7.egg/datasets/arrow_reader.py", line 322, in read_table
    stream = stream_from(filename)
  File "pyarrow/io.pxi", line 782, in pyarrow.lib.memory_map
  File "pyarrow/io.pxi", line 743, in pyarrow.lib.MemoryMappedFile._open
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Memory mapping file failed: Cannot allocate memory

@lhoestq

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting
Some wikipedia configurations do require the user to have `apache_beam` in order to parse the wikimedia data.

On the other hand regarding your second issue
```
OSError: Memory mapping file failed: Cannot allocate memory
```
I've never experienced this, can you open a new issue for this specific error and provide more details please ?

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one is out of scope on the current architecture.

The `MissingBeamOptions` / `No module named 'apache_beam'` error is specific to the old script-based Wikipedia loader (`wikipedia/wikipedia.py` with the `20200501.*` configs), which relied on Apache Beam. That code path is gone:

- `src/datasets/load.py:1661-1666` — `load_dataset` no longer supports script-based loading; the error message explicitly tells users to use datasets converted to "a standard format like Parquet".
- There is no longer a `datasets/wikipedia/` directory in this repo; the maintained Wikipedia dataset is now hosted as Parquet on the Hub (e.g. `wikimedia/wikipedia` on https://huggingface.co/datasets/wikimedia/wikipedia), which works without Apache Beam.

For a current workflow:
```python
ds = load_dataset("wikimedia/wikipedia", "20231101.aa", split="train")
```

Would you mind closing this out? If you hit a specific issue with the Hub-hosted Wikipedia, that's better tracked on the Hub repo's discussion tab.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch at commit 19302564.)
