### ISSUE TITLE
Issue: Dataset download error

### ISSUE THREAD

**Issue by XuhuiZhou** [huggingface/datasets#2076]
The download link in `iwslt2017.py` file does not seem to work anymore.

For example, `FileNotFoundError: Couldn't find file at https://wit3.fbk.eu/archive/2017-01-trnted/texts/zh/en/zh-en.tgz`

Would be nice if we could modify it script and use the new downloadable link?

**Comment by albertvillanova** [comment]
Hi @XuhuiZhou, thanks for reporting this issue. 

Indeed, the old links are no longer valid (404 Not Found error), and the script must be updated with the new links to Google Drive.

**Comment by lhoestq** [comment]
It would be nice to update the urls indeed !

To do this, you just need to replace the urls in `iwslt2017.py` and then update the dataset_infos.json file with
```
datasets-cli test ./datasets/iwslt2017 --all_configs --save_infos --ignore_verifications
```

**Comment by XuhuiZhou** [comment]
Is this a command to update my local files or fix the file Github repo in general? (I am not so familiar with the datasets-cli command here)

**Comment by lhoestq** [comment]
This command will update your local file. Then you can open a Pull Request to push your fix to the github repo :)
And yes you are right, it is a "canonical" dataset, i.e. a dataset script defined in this github repo (as opposed to dataset repositories of users on the huggingface hub)

**Comment by XuhuiZhou** [comment]
Hi, thanks for the answer. 

I gave a try to the problem today. But I encountered an upload error: 

```
git push -u origin fix_link_iwslt
Enter passphrase for key '/home2/xuhuizh/.ssh/id_rsa': 
ERROR: Permission to huggingface/datasets.git denied to XuhuiZhou.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any insight here? 

By the way, when I run the datasets-cli command, it shows the following error, but does not seem to be the error coming from `iwslt.py`

```
Traceback (most recent call last):
  File "/home2/xuhuizh/anaconda3/envs/UMT/bin/datasets-cli", line 33, in <module>
    sys.exit(load_entry_point('datasets', 'console_scripts', 'datasets-cli')())
  File "/home2/xuhuizh/projects/datasets/src/datasets/commands/datasets_cli.py", line 35, in main
    service.run()
  File "/home2/xuhuizh/projects/datasets/src/datasets/commands/test.py", line 141, in run
    try_from_hf_gcs=False,
  File "/home2/xuhuizh/projects/datasets/src/datasets/builder.py", line 579, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/home2/xuhuizh/projects/datasets/src/datasets/builder.py", line 639, in _download_and_prepare
    self.info.download_checksums, dl_manager.get_recorded_sizes_checksums(), "dataset source files"
  File "/home2/xuhuizh/projects/datasets/src/datasets/utils/info_utils.py", line 32, in verify_checksums
    raise ExpectedMoreDownloadedFiles(str(set(expected_checksums) - set(recorded_checksums)))
datasets.utils.info_utils.ExpectedMoreDownloadedFiles: {'https://wit3.fbk.eu/archive/2017-01-trnmted//texts/DeEnItNlRo/DeEnItNlRo/DeEnItNlRo-DeEnItNlRo.tgz'}
```

**Comment by lhoestq** [comment]
Hi ! To create a PR on this repo your must fork it and create a branch on your fork. See how to fork the repo [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md#start-by-preparing-your-environment).
And to make the command work without the `ExpectedMoreDownloadedFiles` error, you just need to use the `--ignore_verifications` flag.

**Comment by albertvillanova** [comment]
Hi @XuhuiZhou,

As @lhoestq has well explained, you need to fork HF's repository, create a feature branch in your fork, push your changes to it and then open a Pull Request to HF's upstream repository. This is so because at HuggingFace Datasets we follow a development model called "Fork and Pull Model". You can find more information here:
- [Understanding the GitHub flow](https://guides.github.com/introduction/flow/)
- [Forking Projects](https://guides.github.com/activities/forking/)

Alternatively, if you find all these steps too complicated, you can use the GitHub official command line tool: [GitHub CLI](https://cli.github.com/). Once installed, in order to create a Pull Request, you only need to use this command:
```shell
gh pr create --web
```
This utility will automatically create the fork, push your changes and open a Pull Request, under the hood.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one is out of scope on the current architecture.

The broken FBK download link lived in the old `iwslt2017.py` loading script. Script-based loading has been removed from `datasets`, so this codebase no longer hosts the URL that needs patching:

- `src/datasets/load.py:1661-1666` — `load_dataset` no longer supports loading scripts; the message instructs users to ask dataset authors to "convert it to a standard format like Parquet."
- The repo no longer has a top-level `datasets/iwslt2017/` directory; IWSLT data is now reached via its Hub dataset repo (https://huggingface.co/datasets/iwslt2017), where URL maintenance has to happen.

If a specific Hub dataset for IWSLT2017 still ships a dead URL, the dataset repo's discussion tab on the Hub is the place to flag it. Otherwise I'd suggest closing this out.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch at commit 19302564.)
