### ISSUE TITLE
Bug in wiki bio load

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/datasets#3580]
wiki_bio is failing to load because of a failing drive link . Can someone fix this ?

![7E90023B-A3B1-4930-BA25-45CCCB4E1710](https://user-images.githubusercontent.com/3104771/149617870-5a32a2da-2c78-483b-bff6-d7534215a423.png)

![653C1C76-C725-4A04-A0D8-084373BA612F](https://user-images.githubusercontent.com/3104771/149617875-ef0e30b0-b76e-48cf-b3eb-93ba8e6e5465.png)
a

**Comment by jxmorris12** [comment]
+1, here's the error I got: 

```
>>> from datasets import load_dataset
>>>
>>> load_dataset("wiki_bio")
Downloading: 7.58kB [00:00, 4.42MB/s]
Downloading: 2.71kB [00:00, 1.30MB/s]
Using custom data configuration default
Downloading and preparing dataset wiki_bio/default (download: 318.53 MiB, generated: 736.94 MiB, post-processed: Unknown size, total: 1.03 GiB) to /home/jxm3/.cache/huggingface/datasets/wiki_bio/default/1.1.0/5293ce565954ba965dada626f1e79684e98172d950371d266bf3caaf87e911c9...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/load.py", line 1694, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/builder.py", line 595, in download_and_prepare
    self._download_and_prepare(
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/builder.py", line 662, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/jxm3/.cache/huggingface/modules/datasets_modules/datasets/wiki_bio/5293ce565954ba965dada626f1e79684e98172d950371d266bf3caaf87e911c9/wiki_bio.py", line 125, in _split_generators
    data_dir = dl_manager.download_and_extract(my_urls)
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/download_manager.py", line 308, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/download_manager.py", line 196, in download
    downloaded_path_or_paths = map_nested(
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 251, in map_nested
    return function(data_struct)
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/download_manager.py", line 217, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 298, in cached_path
    output_path = get_from_cache(
  File "/home/jxm3/.conda/envs/torch/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 612, in get_from_cache
    raise FileNotFoundError(f"Couldn't find file at {url}")
FileNotFoundError: Couldn't find file at https://drive.google.com/uc?export=download&id=1L7aoUXzHPzyzQ0ns4ApBbYepsjFOtXil
>>>
```

**Comment by jxmorris12** [comment]
@alejandrocros and @lhoestq - you added the wiki_bio dataset in #1173. It doesn't work anymore. Can you take a look at this?

**Comment by jxmorris12** [comment]
And if something is wrong with Google Drive, you could try to download (and collate and unzip) from here: https://github.com/DavidGrangier/wikipedia-biography-dataset

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting. I've downloaded the data and concatenated them into a zip file available here: https://huggingface.co/datasets/wiki_bio/tree/main/data

I guess we can update the dataset script to use this zip file now :)
