### ISSUE TITLE
conll 2003 dataset source url is no longer valid

### ISSUE THREAD

**Issue by rcanand** [huggingface/datasets#3582]
## Describe the bug
Loading `conll2003` dataset fails because it was removed (just yesterday 1/14/2022) from the location it is looking for.

## Steps to reproduce the bug
```python
from datasets import load_dataset


load_dataset("conll2003")
```

## Expected results
The dataset should load.

## Actual results
It is looking for the dataset at `https://github.com/davidsbatista/NER-datasets/raw/master/CONLL2003/train.txt` but it was removed from there yesterday (see [commit](https://github.com/davidsbatista/NER-datasets/commit/9d8f45cc7331569af8eb3422bbe1c97cbebd5690) that removed the file and related [issue](https://github.com/davidsbatista/NER-datasets/issues/8)). 

- We should replace this with an alternate valid location.
- this is being referenced in the huggingface course chapter 7 [colab notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/chapter7/section2_pt.ipynb), which is also broken.

```python
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-27c956bec93c> in <module>()
      1 from datasets import load_dataset
      2 
----> 3 raw_datasets = load_dataset("conll2003")

11 frames
/usr/local/lib/python3.7/dist-packages/datasets/utils/file_utils.py in get_from_cache(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent, local_files_only, use_etag, max_retries, use_auth_token, ignore_url_params)
    610             )
    611         elif response is not None and response.status_code == 404:
--> 612             raise FileNotFoundError(f"Couldn't find file at {url}")
    613         _raise_if_offline_mode_is_enabled(f"Tried to reach {url}")
    614         if head_error is not None:

FileNotFoundError: Couldn't find file at https://github.com/davidsbatista/NER-datasets/raw/master/CONLL2003/train.txt
```

## Environment info

- `datasets` version:
- Platform:
- Python version:
- PyArrow version:

**Comment by GuillemGSubies** [comment]
I came to open the same issue.

**Comment by lhoestq** [comment]
Thanks for reporting !

I pushed a temporary fix on `master` that uses an URL from a previous commit to access the dataset for now, until we have a better solution

**Comment by lhoestq** [comment]
I changed the URL again to use another host, the fix is available on `master` and we'll probably do a new release of `datasets` tomorrow.

In the meantime, feel free to do `load_dataset(..., revision="master")` to use the fixed script

**Comment by lhoestq** [comment]
We just released a new version of `datasets` with a working URL. Feel free to update `datasets` and try again :)

**Comment by dafedo** [comment]
Hello! Unfortunately, this URL does not work for me. 
Could you please tell me how I can solve the problem?

`>>> from datasets import load_dataset
>>> dataset = load_dataset("conll2003")
Downloading and preparing dataset conll2003/conll2003 (download: 4.63 MiB, generated: 9.78 MiB, post-processed: Unknown size, total: 14.41 MiB) to /home/dafedo/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/load.py", line 745, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/builder.py", line 574, in download_and_prepare
    self._download_and_prepare(
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/builder.py", line 630, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/dafedo/.cache/huggingface/modules/datasets_modules/datasets/conll2003/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6/conll2003.py", line 196, in _split_generators
    downloaded_files = dl_manager.download_and_extract(urls_to_download)
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 287, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 195, in download
    downloaded_path_or_paths = map_nested(
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 203, in map_nested
    mapped = [
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 204, in <listcomp>
    _single_map_nested((function, obj, types, None, True)) for obj in tqdm(iterable, disable=disable_tqdm)
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 142, in _single_map_nested
    return function(data_struct)
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 218, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 281, in cached_path
    output_path = get_from_cache(
  File "/home/dafedo/efficient-task-transfer/venv/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 621, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://github.com/davidsbatista/NER-datasets/raw/master/CONLL2003/train.txt
`

I receive the same error when I run "itrain run_configs/conll2003.json" from https://github.com/adapter-hub/efficient-task-transfer

Thank you very much in advance!

Regards, 
Daria

**Comment by lhoestq** [comment]
Can you try updating `datasets` and try again ?
```
pip install -U datasets
```

**Comment by dafedo** [comment]
Thank you very much for your answer! 

It works this way, but for my research I need datasets==1.6.3 or closest to it because otherwise the other package would not work as it is built on this version.
Do you have any other suggestion? I would really appreciate it. Maybe which version of the datasets is without hard-coded link but closest to 1.6.3

**Comment by dafedo** [comment]
No problem, I have solved it. 
Thank you anyway.

**Comment by lhoestq** [comment]
Out of curiosity, which package has the `datasets==1.6.3` requirement ?
