### ISSUE TITLE
I can view HFcallback for ASR Space

### ISSUE THREAD

**Issue by kingabzpro** [huggingface/datasets#3978]
## Dataset viewer issue for '*Urdu-ASR-flags*'

**Link:** *[link to the dataset viewer page](https://huggingface.co/datasets/kingabzpro/Urdu-ASR-flags)*

*I think dataset should show some thing and if you want me to add script, please show me the documentation. I thought this was suppose to be automatic task.*

Am I the one who added this dataset ? Yes

**Comment by severo** [comment]
the dataset viewer is working on this dataset. I imagine the issue is that we would expect to be able to listen to the audio files in the `Please Record Your Voice file` column, right?

maybe @lhoestq or @albertvillanova could help

<img width="1019" alt="Capture d’écran 2022-03-24 à 17 36 20" src="https://user-images.githubusercontent.com/1676121/159966006-57dcf8f7-b65f-4200-ac8c-66859318a8bb.png">

**Comment by lhoestq** [comment]
The structure of the dataset is not supported. Only the CSV file is parsed and the audio files are ignored.

We're working on supporting audio datasets with a specific structure in #3963

**Comment by kingabzpro** [comment]
Got it.

**Comment by severo** [comment]
Current error:

```
Error code:   StreamingRowsError
Exception:    LibsndfileError
Message:      Error opening <File-like object HfFileSystem, datasets/kingabzpro/Urdu-ASR-flags@6a8878cfe3a41343fa86ec8b4254209fe56a0f0d/Please Record Your Voice/0.wav>: Format not recognised.
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/utils.py", line 263, in get_rows_or_raise
                  return get_rows(
                File "/src/services/worker/src/worker/utils.py", line 204, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/utils.py", line 241, in get_rows
                  rows_plus_one = list(itertools.islice(ds, rows_max_number + 1))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 1357, in __iter__
                  example = _apply_feature_types_on_example(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 1051, in _apply_feature_types_on_example
                  decoded_example = features.decode_example(encoded_example, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1902, in decode_example
                  return {
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1903, in <dictcomp>
                  column_name: decode_nested_example(feature, value, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1325, in decode_nested_example
                  return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/audio.py", line 187, in decode_example
                  array, sampling_rate = sf.read(f)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/soundfile.py", line 285, in read
                  with SoundFile(file, 'r', samplerate, channels,
                File "/src/services/worker/.venv/lib/python3.9/site-packages/soundfile.py", line 658, in __init__
                  self._file = self._open(file, mode_int, closefd)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/soundfile.py", line 1216, in _open
                  raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
              soundfile.LibsndfileError: Error opening <File-like object HfFileSystem, datasets/kingabzpro/Urdu-ASR-flags@6a8878cfe3a41343fa86ec8b4254209fe56a0f0d/Please Record Your Voice/0.wav>: Format not recognised.
```

Maybe switch to a discussion here? https://huggingface.co/datasets/kingabzpro/Urdu-ASR-flags/discussions. cc @albertvillanova
