### ISSUE TITLE
Permission denied: '/home/.cache' when load_dataset with local script

### ISSUE THREAD

**Issue by jiangh0** [huggingface/datasets#4589]
Traceback (most recent call last):
  File "/data6/hadoop/yarn/nm-local-dir/usercache/hadoop-aipnlp/appcache/application_1655713348720_6618870/container_e106_1655713348720_6618870_01_000002/run_ner_no_trainer.py", line 698, in <module>
    main()
  File "/data6/hadoop/yarn/nm-local-dir/usercache/hadoop-aipnlp/appcache/application_1655713348720_6618870/container_e106_1655713348720_6618870_01_000002/run_ner_no_trainer.py", line 283, in main
    raw_datasets = load_dataset('src/utils/load_dataset_json.py', cache_dir='/mnt/docker/user/jiang/.cache/huggingface/datasets', data_files=data_files, field='data')
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/load.py", line 1704, in load_dataset
    builder_instance = load_dataset_builder(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/load.py", line 1530, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/load.py", line 1200, in dataset_module_factory
    return LocalDatasetModuleFactoryWithScript(
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/load.py", line 734, in get_module
    dynamic_modules_path = self.dynamic_modules_path if self.dynamic_modules_path else init_dynamic_modules()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/load.py", line 92, in init_dynamic_modules
    hf_modules_cache = init_hf_modules(hf_modules_cache)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 53, in init_hf_modules
    os.makedirs(hf_modules_cache, exist_ok=True)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/jianghao30/miniconda3/envs/uni_pytorch/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/.cache'

**Comment by jiangh0** [comment]
when I use local script to load my own datasets, the dataset and script will be cached. 
How to forbin this behavior? my machine don't have internet access and root permissions.

**Comment by jiangh0** [comment]
code:
raw_datasets = load_dataset('src/utils/load_dataset_json.py', cache_dir='/mnt/*****/user/******/.cache/huggingface/datasets', data_files=data_files, field='data')
