### ISSUE TITLE
WMT19 custom download checksum error

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/datasets#5500]
### Describe the bug

I use the following scripts to download data from WMT19:
```python
import datasets
from datasets import inspect_dataset, load_dataset_builder
from wmt19.wmt_utils import _TRAIN_SUBSETS,_DEV_SUBSETS

## this is a must due to: https://discuss.huggingface.co/t/load-dataset-hangs-with-local-files/28034/3
if __name__ == '__main__':
    dev_subsets,train_subsets = [],[]
    for subset in _TRAIN_SUBSETS:
        if subset.target=='en' and 'de' in subset.sources:
            train_subsets.append(subset.name)
    for subset in _DEV_SUBSETS:
        if subset.target=='en' and 'de' in subset.sources:
            dev_subsets.append(subset.name)

    inspect_dataset("wmt19", "./wmt19")
    builder = load_dataset_builder(
        "./wmt19/wmt_utils.py",
        language_pair=("de", "en"),
        subsets={
            datasets.Split.TRAIN: train_subsets,
            datasets.Split.VALIDATION: dev_subsets,
        },
        
    )

    builder.download_and_prepare()
    ds = builder.as_dataset()
    ds.to_json("../data/wmt19/ende/data.json")
```
And I got the following error:
```
Traceback (most recent call last):                                                                                      | 0/2 [00:00<?, ?obj/s]
  File "draft.py", line 26, in <module>
    builder.download_and_prepare()                                                                                      | 0/1 [00:00<?, ?obj/s]
  File "/Users/hannibal046/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 605, in download_and_prepare
    self._download_and_prepare(%|                                                                                       | 0/1 [00:00<?, ?obj/s]
  File "/Users/hannibal046/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 1104, in _download_and_prepare
    super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos)                          | 0/1 [00:00<?, ?obj/s]
  File "/Users/hannibal046/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 676, in _download_and_prepare
    verify_checksums(s #13:   0%|                                                                                       | 0/1 [00:00<?, ?obj/s]
  File "/Users/hannibal046/anaconda3/lib/python3.8/site-packages/datasets/utils/info_utils.py", line 35, in verify_checksums
    raise UnexpectedDownloadedFile(str(set(recorded_checksums) - set(expected_checksums)))                              | 0/1 [00:00<?, ?obj/s]
datasets.utils.info_utils.UnexpectedDownloadedFile: {'https://s3.amazonaws.com/web-language-models/paracrawl/release1/paracrawl-release1.en-de.zipporah0-dedup-clean.tgz', 'https://huggingface.co/datasets/wmt/wmt13/resolve/main-zip/training-parallel-europarl-v7.zip', 'https://huggingface.co/datasets/wmt/wmt18/resolve/main-zip/translation-task/rapid2016.zip', 'https://huggingface.co/datasets/wmt/wmt18/resolve/main-zip/translation-task/training-parallel-nc-v13.zip', 'https://huggingface.co/datasets/wmt/wmt17/resolve/main-zip/translation-task/training-parallel-nc-v12.zip', 'https://huggingface.co/datasets/wmt/wmt14/resolve/main-zip/training-parallel-nc-v9.zip', 'https://huggingface.co/datasets/wmt/wmt15/resolve/main-zip/training-parallel-nc-v10.zip', 'https://huggingface.co/datasets/wmt/wmt16/resolve/main-zip/translation-task/training-parallel-nc-v11.zip'}

```

### Steps to reproduce the bug

see above

### Expected behavior

download data successfully

### Environment info

datasets==2.1.0
python==3.8

**Comment by Hannibal046** [comment]
I update the `datatsets` version and it works.
