### ISSUE TITLE
Invalid Arrow data from JSONL

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#5531]
This code fails:
```python
from datasets import Dataset

ds = Dataset.from_json(path_to_file)
ds.data.validate()
```
raises

```python
ArrowInvalid: Column 2: In chunk 1: Invalid: Struct child array #3 invalid: Invalid: Length spanned by list offsets (4064) larger than values array (length 4063)
```

This causes many issues for @TevenLeScao:

- `map` fails because it fails to rewrite invalid arrow arrays

    ```python
    ~/Desktop/hf/datasets/src/datasets/arrow_writer.py in write_examples_on_file(self)
        438             if all(isinstance(row[0][col], (pa.Array, pa.ChunkedArray)) for row in self.current_examples):
        439                 arrays = [row[0][col] for row in self.current_examples]
    --> 440                 batch_examples[col] = array_concat(arrays)
        441             else:
        442                 batch_examples[col] = [

    ~/Desktop/hf/datasets/src/datasets/table.py in array_concat(arrays)
    1885 
    1886     if not _is_extension_type(array_type):
    -> 1887         return pa.concat_arrays(arrays)
    1888 
    1889     def _offsets_concat(offsets):

    ~/.virtualenvs/hf-datasets/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.concat_arrays()

    ~/.virtualenvs/hf-datasets/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

    ~/.virtualenvs/hf-datasets/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

    ArrowIndexError: array slice would exceed array length
    ```

- `to_dict()` **segfaults** ⚠️

    ```python
    /Users/runner/work/crossbow/crossbow/arrow/cpp/src/arrow/array/data.cc:99:  Check failed: (off) <= (length) Slice offset greater 
    than array length
    ```

To reproduce: unzip the archive and run the above code using `sanity_oscar_en.jsonl`
[sanity_oscar_en.jsonl.zip](https://github.com/huggingface/datasets/files/10734124/sanity_oscar_en.jsonl.zip)

**Comment by AngledLuffa** [comment]
Can I bump this?  I am still running into the same crash, or a similar crash, a few years later:

```
>>> from datasets import load_dataset
>>> ds = load_dataset('oscar-corpus/community-oscar', data_files='data/2024-38/sd_meta/*.jsonl.zst', split='train', streaming=False)
data/2024-38/sd_meta/sd_meta.jsonl.zst: 100%|██████████████████████████████████████████████████████████████████████████████| 39.4M/39.4M [00:02<00:00, 14.2MB/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/builder.py", line 1871, in _prepare_split_single
    writer.write_table(table)
    ~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/arrow_writer.py", line 642, in write_table
    pa_table = pa_table.combine_chunks()
  File "pyarrow/table.pxi", line 4557, in pyarrow.lib.Table.combine_chunks
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowIndexError: array slice would exceed array length

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    ds = load_dataset('oscar-corpus/community-oscar', data_files='data/2024-38/sd_meta/*.jsonl.zst', split='train', streaming=False)
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/load.py", line 2084, in load_dataset
    builder_instance.download_and_prepare(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        download_config=download_config,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/builder.py", line 925, in download_and_prepare
    self._download_and_prepare(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dl_manager=dl_manager,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        **download_and_prepare_kwargs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/builder.py", line 1001, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/builder.py", line 1742, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        gen_kwargs=gen_kwargs, job_id=job_id, **_prepare_split_args
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/nlp/scr/horatio/miniconda3/lib/python3.13/site-packages/datasets/builder.py", line 1898, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset
>>>
```

**Comment by lhoestq** [comment]
This is likely an issue to report on pyarrow. Do you know what's causing this in the data ? Is there a malformed JSON somewhere or something like that ?

**Comment by AngledLuffa** [comment]
I don't know anything about the underlying causes, unfortunately.  I just found this issue while trying to figure out why I couldn't use `load_dataset` on Oscar community crawl.

**Comment by ebarkhordar** [comment]
**Correction, 2026-08-09.** The second of the two workarounds above is wrong, and I have now run it instead of reasoning about it. There is no `chunksize` that avoids the bug, and in a band of values it makes things worse.

The knob is `chunksize`, which `json.py:229` turns into pyarrow's `block_size` as `chunksize // 32`; `json.py:286` widens that to the batch length only when `len(batch) // 8` exceeds it. On a 38.5 MB synthetic file with the reported shape (a leading `null` in `meta.line_identifications`), clean `python:3.12-slim`, `datasets` 5.0.1, pyarrow 25.0.0:

```
chunksize        Dataset.from_json(path, chunksize=...)
10MB (default)   ArrowInvalid, chunk 54
32MB             ArrowInvalid, chunk 174
64MB             ArrowInvalid, chunk 199
512MB            ArrowIndexError: array slice would exceed array length
1GB              ArrowIndexError: array slice would exceed array length
2GB              ArrowInvalid, chunk 199
```

The two `ArrowIndexError` rows are the crash from the top of this thread, reached from the other side. Traced at the `read_json` call, 512MB and 1GB give `block_size` 16MB and 32MB against a single 38.5 MB batch, so the batch is split into blocks again; 2GB gives 64MB, one block, and the original `ArrowInvalid` comes back. This is a synthetic file, not the gated one from the traceback above, so the boundary values are a property of that file, not a threshold to aim for.

The workaround that does work is the one already in the issue body: `Dataset.from_pandas(pd.read_json(path, lines=True))`, with the RAM caveat noted there. Same file, same container: 200000 rows, `validate(full=True)` clean. I should have pointed at that rather than offering an untested alternative.

The root cause below and the `parser.cc` reading are unchanged.

The data is not malformed. `pyarrow.json.read_json` builds an invalid `ListArray` when a list's **leading** elements are `null` and the element type is only established later in the same block. The offsets count those nulls, the child values array does not.

One line reproduces it, no `datasets` involved:

```python
import io, pyarrow.json as paj
t = paj.read_json(io.BytesIO(b'{"a":[null,1]}'))
print(t.column(0).chunk(0).offsets.to_pylist(), len(t.column(0).chunk(0).values))
# [0, 2] 1
t.validate(full=True)
# ArrowInvalid: Column 0: In chunk 0: Invalid: Length spanned by list offsets (2) larger than values array (length 1)
```

The child is short by exactly the number of nulls preceding the first typed element of that field **in the block**, so it is position dependent, not value dependent:

```
{"a":[1]}         {"a":[null,2]}          -> valid, nothing lost
{"a":[null,2]}    {"a":[1]}               -> invalid, 1 slot missing
{"a":[null,null,1]} {"a":[null,2]}        -> invalid, 2 missing (only the first run is lost)
```

It is not struct specific either: `[null,1]`, `[null,"s"]` and `[null,[1]]` all do it. Same result on pyarrow 25.0.0, 18.1.0, 14.0.2 and 11.0.0, so it is not a recent regression.

That block dependence is why the file you attached looks intermittent. Running `paj.read_json` on `sanity_oscar_en.jsonl` directly:

```
block_size = 1 MiB (default)   72 chunks   ArrowInvalid, Column 2, chunk 2  (5651 vs 5647)
block_size = 10 MiB             8 chunks   ArrowInvalid, Column 2, chunk 1  (72341 vs 72338)
block_size = 100 MiB            1 chunk    validate() ok
```

Column 2 is `meta` and struct child #3 is `meta.line_identifications`. Of the 10000 rows, 6706 have at least one `null` entry in that list and 945 start with one. Only the 945 can corrupt a block, and only when they land at the start of one, which is why a single large block reads clean.

`read_json` returns without raising, which is why the failure surfaces far from its cause. Against the same attached file:

```python
t = paj.read_json(path, read_options=paj.ReadOptions(block_size=1<<20))  # no error, 10000 rows
t.combine_chunks()
# ArrowIndexError: array slice would exceed array length
```

That is @AngledLuffa's traceback, at `arrow_writer.py` `pa_table.combine_chunks()`. I could not fetch `oscar-corpus/community-oscar` (gated, HTTP 401), so I am not claiming to have reproduced those exact bytes, only that the file in your original report produces that error at that call.

Two things that avoid it, if either is useful:

- `ParseOptions(explicit_schema=...)`, since nothing has to be promoted from null. `[null,null,1]` validates clean with a schema supplied. `datasets` calls `paj.read_json` with `read_options` only (`src/datasets/packaged_modules/json/json.py:290`), so `features=` does not reach it today: on a two-line file starting with `{"a":[null,1]}`, `Dataset.from_json(path, features=Features({"a": Sequence(Value("int64"))}))` is still invalid on `main`, with and without `features`.
- A block large enough that a typed element for the field is seen before any leading-null list.

Reading `cpp/src/arrow/json/parser.cc` at arrow `8fba4393`, the shape that fits is that nulls for an untyped builder are counted inline in `BuilderPtr::index`, and `AppendNull` (line 532, `kNull` case at 537-552) increments a by-value copy at line 543 and writes it back to the *parent* only. A struct field picks the new count back up on the next key (`SetFieldBuilder`, line 855), but a list value builder is read once in `StartArrayImpl` (line 886) and never re-read, so `MaybePromoteFromNull` (line 1144) promotes with a stale count and creates the child with no leading nulls. I have not built Arrow to confirm that, so treat this paragraph as a code reading. Everything above it is measured.

Verified in a clean `python:3.12-slim` container today: `datasets` at `b7cb10b0` (5.0.2.dev0), pyarrow 25.0.0, plus the version sweep above. I did not find an existing apache/arrow issue for this (searched for "Length spanned by list offsets" and JSON/null title combinations). Happy to file it upstream with the one-liner if you would like.

**Comment by AngledLuffa** [comment]
Not my monkeys, not my circus, but: it seems like there's a *vast* difference between posting some useful suggestions, even if it's written by an LLM, and just slapping a bug report into an LLM and then pasting the output into the comment box.  I'm a strong believer in using coding agents and I'd be embarrassed to post this kind of followup.

**Comment by behroozazarkhalili** [comment]
Root cause, reproduced with pyarrow 25.0.0 and no datasets involved: when a list column's first elements are null and the JSON reader infers the type, it keeps the offsets for those nulls but drops their values, so the table it returns fails `validate(full=True)` with "Length spanned by list offsets larger than values array". A one-row file such as `{"a":[null,1]}` with a small `block_size` triggers it; in the file attached here it is `meta.line_identifications` (column 2, struct child 3), which starts with four nulls.

I filed it upstream as apache/arrow#51305 with the pyarrow-only reproducer.

On the datasets side I am preparing a small guard for the JSON loader: validate each table pyarrow returns, and when it is invalid re-read that file as a single block (falling back to the pandas path only if that is invalid too) so an invalid table never reaches `map` or `combine_chunks`. Validation costs about 5% of the parse time on the 74 MB file from this thread.
