### ISSUE TITLE
Unable to use BLEURT in offline mode

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/datasets#5599]
### Describe the bug

Trying to use BLEURT in offline mode fails. The script and model weights are cached to disk fine (when not in offline mode). In offline mode, it loads the script from the cache fine, but when trying to load the cached model weights, it throws an error.

### Steps to reproduce the bug

Steps to reproduce the behaviour:

```python
from datasets import load_metric

import os
os.environ["HF_DATASETS_OFFLINE"] = "1"

bleurt = load_metric("bleurt")
```

Gives the following error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/utils/deprecation_utils.py", line 46, in wrapper
    return deprecated_function(*args, **kwargs)
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/load.py", line 1397, in load_metric
    metric.download_and_prepare(download_config=download_config)
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/metric.py", line 625, in download_and_prepare
    self._download_and_prepare(dl_manager)
  File "/home/johnmg/.cache/huggingface/modules/datasets_modules/metrics/bleurt/89f7c298fa543e9cee6749e6ed198069d7c10fc8e99c0ff37a843dbc0eea88d7/bleurt.py", line 117, in _download_and_prepare
    model_path = dl_manager.download_and_extract(CHECKPOINT_URLS[checkpoint_name])
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/download/download_manager.py", line 564, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/download/download_manager.py", line 427, in download
    downloaded_path_or_paths = map_nested(
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 436, in map_nested
    return function(data_struct)
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/download/download_manager.py", line 453, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 182, in cached_path
    output_path = get_from_cache(
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 530, in get_from_cache
    _raise_if_offline_mode_is_enabled(f"Tried to reach {url}")
  File "/home/johnmg/mediqa/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 260, in _raise_if_offline_mode_is_enabled
    raise OfflineModeIsEnabled(
datasets.utils.file_utils.OfflineModeIsEnabled: Offline mode is enabled. Tried to reach https://storage.googleapis.com/bleurt-oss/bleurt-base-128.zip
```

### Expected behavior

I would expect that, after loading the metric as `bleurt = load_metric("bleurt")` _with_ an internet connection it will be cached locally, and I should be able to load it from this cache _without_ an internet connection afterwards.

### Environment info

I installed datasets from source with `pip install git+https://github.com/huggingface/datasets.git`

**Comment by lhoestq** [comment]
Hi ! Metric related issues should be posted in the [evaluate repository](https://github.com/huggingface/evaluate) - happy to help from there ;)
