### ISSUE TITLE
Cannot import datasets

### ISSUE THREAD

**Issue by eerio** [huggingface/datasets#5633]
### Describe the bug

Hi,

I cannot even import the library :( I installed it by running:
```
$ conda install datasets
```
Then I realized I should maybe use the huggingface channel, because I encountered the error below, so I ran:
```
$ conda remove datasets 
$ conda install -c huggingface datasets
```
Please see 'steps to reproduce the bug' for the specific error, as steps to reproduce is just importing the library

### Steps to reproduce the bug

```
$ python3 
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/datasets/__init__.py", line 33, in <module>
    from .arrow_dataset import Dataset, concatenate_datasets
  File "/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 59, in <module>
    from .arrow_reader import ArrowReader
  File "/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/datasets/arrow_reader.py", line 27, in <module>
    import pyarrow.parquet as pq
  File "/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/pyarrow/parquet/__init__.py", line 20, in <module>
    from .core import *
  File "/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 37, in <module>
    from pyarrow._parquet import (ParquetReader, Statistics,  # noqa
ImportError: cannot import name 'FileEncryptionProperties' from 'pyarrow._parquet' (/home/jack/.conda/envs/jack_zpp/lib/python3.8/site-packages/pyarrow/_parquet.cpython-38-x86_64-linux-gnu.so)
```

### Expected behavior

I would expect for the statement `import datasets` to cause no error

### Environment info

Output of `conda list`:
```
# packages in environment at /home/jack/.conda/envs/pbalawender_zpp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
abseil-cpp                20210324.2           h2531618_0  
advertools                0.13.2                   pypi_0    pypi
aiofiles                  0.8.0                    pypi_0    pypi
aiohttp                   3.8.3            py38h5eee18b_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
aiosqlite                 0.17.0                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
aquirdturtle-collapsible-headings 3.1.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
arrow-cpp                 3.0.0            py38h6b21186_4  
asttokens                 2.2.0                    pypi_0    pypi
async-timeout             4.0.2            py38h06a4308_0  
attrs                     22.1.0           py38h06a4308_0  
automat                   22.10.0                  pypi_0    pypi
aws-c-common              0.4.57               he6710b0_1  
aws-c-event-stream        0.1.6                h2531618_5  
aws-checksums             0.1.9                he6710b0_0  
aws-sdk-cpp               1.8.185              hce553d0_0  
babel                     2.11.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    5.0.1                    pypi_0    pypi
boost-cpp                 1.73.0              h27cfd23_11  
bottleneck                1.3.5            py38h7deecbd_0  
brotli                    1.0.9                h5eee18b_7  
brotli-bin                1.0.9                h5eee18b_7  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.9.24                pypi_0    pypi
cffi                      1.15.1           py38h5eee18b_3  
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cryptography              38.0.4                   pypi_0    pypi
cssselect                 1.2.0                    pypi_0    pypi
cudatoolkit               10.1.243            h8cb64d8_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
dacite                    1.6.0                    pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7  
datasets                  1.18.4                     py_0    huggingface
datetime                  4.7                      pypi_0    pypi
debugpy                   1.6.4                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.6            py38h06a4308_0  
docker-pycreds            0.4.0                    pypi_0    pypi
double-conversion         3.1.5                he6710b0_1  
entrypoints               0.4              py38h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
filelock                  3.8.0                    pypi_0    pypi
flake8                    6.0.0                    pypi_0    pypi
flask                     2.1.3            py38h06a4308_0  
flit-core                 3.6.0              pyhd3eb1b0_0  
fonttools                 4.38.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3            py38h5eee18b_0  
fsspec                    2022.11.0        py38h06a4308_0  
gensim                    4.2.0                    pypi_0    pypi
gflags                    2.2.2                he6710b0_0  
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.30                   pypi_0    pypi
glog                      0.5.0                h2531618_0  
grpc-cpp                  1.39.0               hae934f6_5  
huggingface-hub           0.11.1                   pypi_0    pypi
huggingface_hub           0.13.1                     py_0    huggingface
hyperlink                 21.0.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4              py38h06a4308_0  
importlib-metadata        5.1.0                    pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       5.2.0              pyhd3eb1b0_1  
incremental               22.10.0                  pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.17.1             pyh210e3f2_0    conda-forge
ipython                   8.7.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge
isoduration               20.11.0                  pypi_0    pypi
itemadapter               0.7.0                    pypi_0    pypi
itemloaders               1.0.6                    pypi_0    pypi
itsdangerous              2.0.1              pyhd3eb1b0_0  
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2            py38h06a4308_0  
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
json5                     0.9.10                   pypi_0    pypi
jsonpickle                3.0.0                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3           py38h06a4308_0  
jupyter-core              5.1.0                    pypi_0    pypi
jupyter-events            0.5.0                    pypi_0    pypi
jupyter-server            1.23.3                   pypi_0    pypi
jupyter-server-fileid     0.6.0                    pypi_0    pypi
jupyter-server-ydoc       0.4.0                    pypi_0    pypi
jupyter-ydoc              0.2.2                    pypi_0    pypi
jupyter_client            7.4.9            py38h06a4308_0  
jupyter_core              5.2.0            py38h06a4308_0  
jupyterlab                3.6.0a4                  pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.3                   pypi_0    pypi
jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.4               h568e23c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
libboost                  1.73.0              h3ff78a5_11  
libbrotlicommon           1.0.9                h5eee18b_7  
libbrotlidec              1.0.9                h5eee18b_7  
libbrotlienc              1.0.9                h5eee18b_7  
libcurl                   7.88.1               h91b91d3_0  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libnghttp2                1.46.0               hce63b2e_0  
libpng                    1.6.39               h5eee18b_0  
libprotobuf               3.17.2               h4ff587b_1  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0               h1234567_1  
libthrift                 0.14.2               hcc01f38_0  
libtiff                   4.1.0                h2733197_1  
libuv                     1.44.2               h5eee18b_0  
libwebp                   1.2.0                h89dd481_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1            py38h7f8727e_0  
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py38h06a4308_0  
mccabe                    0.7.0                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
morfeusz2                 1.99.6                   pypi_0    pypi
multidict                 6.0.2            py38h5eee18b_0  
multiprocess              0.70.14          py38h06a4308_0  
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.5                    pypi_0    pypi
nbformat                  5.7.0            py38h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py38h06a4308_0  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numexpr                   2.8.4            py38he184ba9_0  
numpy                     1.23.5           py38h14f4228_0  
numpy-base                1.23.5           py38h31eccc5_0  
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
orc                       1.6.9                ha97a36c_3  
packaging                 22.0             py38h06a4308_0  
pandas                    1.5.2                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parsel                    1.7.0                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
pathlib                   1.0.1                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0  
pkgutil-resolve-name      1.3.10           py38h06a4308_0  
platformdirs              2.5.4                    pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.33                   pypi_0    pypi
protego                   0.2.1                    pypi_0    pypi
protobuf                  4.21.12                  pypi_0    pypi
psutil                    5.9.0            py38h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   10.0.1                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydispatcher              2.0.6                    pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0  
pyopenssl                 22.1.0                   pypi_0    pypi
pyrsistent                0.18.0           py38heee7806_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.15               h7a1cb2a_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-dotenv             0.21.0                   pypi_0    pypi
python-fastjsonschema     2.16.2           py38h06a4308_0  
python-json-logger        2.0.4                    pypi_0    pypi
python-xxhash             2.0.2            py38h5eee18b_1  
pytorch                   1.7.1           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0              py38h5eee18b_1  
pyzmq                     23.2.0           py38h6a678d5_0  
queuelib                  1.6.2                    pypi_0    pypi
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.1           py38h06a4308_0  
requests-file             1.5.1                    pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
scrapy                    2.7.1                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentry-sdk                1.12.1                   pypi_0    pypi
service-identity          21.1.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3                   pypi_0    pypi
shortuuid                 1.0.11                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smart-open                6.2.0                    pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
snappy                    1.1.9                h295c915_0  
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.40.1               h5082296_0  
stack-data                0.6.2                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
terminado                 0.17.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tldextract                3.4.0                    pypi_0    pypi
tokenizers                0.13.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torchvision               0.8.2                py38_cu101    pytorch
tornado                   6.2              py38h5eee18b_0  
tqdm                      4.64.1           py38h06a4308_0  
traitlets                 5.6.0                    pypi_0    pypi
transformers              4.25.1                   pypi_0    pypi
tweepy                    4.12.1                   pypi_0    pypi
twisted                   22.10.0                  pypi_0    pypi
twython                   3.9.1                    pypi_0    pypi
typing-extensions         4.4.0            py38h06a4308_0  
typing_extensions         4.4.0            py38h06a4308_0  
uri-template              1.2.0                    pypi_0    pypi
uriparser                 0.9.3                he6710b0_1  
urllib3                   1.26.13                  pypi_0    pypi
utf8proc                  2.6.1                h27cfd23_0  
w3lib                     2.1.0                    pypi_0    pypi
wandb                     0.13.7                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2            py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
widgetsnbextension        4.0.3            py38h06a4308_0  
xxhash                    0.8.0                h7f8727e_3  
xz                        5.2.10               h5eee18b_1  
y-py                      0.5.4                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0  
yarl                      1.8.1            py38h5eee18b_0  
ypy-websocket             0.5.0                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0  
zipp                      3.11.0           py38h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zope-interface            5.5.2                    pypi_0    pypi
zstd                      1.4.9                haebb681_0  
```

**Comment by eerio** [comment]
Okay, the issue was likely caused by mixing `conda` and `pip` usage - I forgot that I have already used `pip` in this environment previously and that it was 'spoiled' because of it. Creating another environment and installing `datasets` by pip with other packages from the `requirements.txt` file solved the problem.
