### ISSUE TITLE
ConnectionError: Couldn't reach https://www.dropbox.com/s/zts98j4vkqtsns6/aclImdb_v2.tar?dl=1

### ISSUE THREAD

**Issue by sauravtii** [huggingface/datasets#5764]
### Describe the bug

I want to use this (https://huggingface.co/datasets/josianem/imdb) dataset therefore I am trying to load it using the following code:

```
raw_datasets = load_dataset("josianem/imdb")
```
The dataset is not getting loaded and gives the error message as the following:

```
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    dataset = load_dataset("josianem/imdb")
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/load.py", line 1112, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 636, in download_and_prepare
    self._download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 704, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/saurav/.cache/huggingface/modules/datasets_modules/datasets/imdb/cc6ab4acab2799be15d5d217c24548b856156dafdc850165fdc4f2031f27ff2f/imdb.py", line 79, in _split_generators
    archive = dl_manager.download(_DOWNLOAD_URL)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 196, in download
    downloaded_path_or_paths = map_nested(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 197, in map_nested
    return function(data_struct)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 217, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 289, in cached_path
    output_path = get_from_cache(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 606, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://www.dropbox.com/s/zts98j4vkqtsns6/aclImdb_v2.tar?dl=1
```

### Steps to reproduce the bug

You can reproduce the error by using the following code:

```
from datasets import load_dataset, load_metric

dataset = load_dataset("josianem/imdb")
```

### Expected behavior

The dataset should get loaded (I am using this dataset for the first time so not much aware of the exact behavior).

### Environment info

- `datasets` version: 1.12.1
- Platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyArrow version: 11.0.0

**Comment by albertvillanova** [comment]
Thanks for reporting, @sauravtii.

Unfortunately, I'm not able to reproduce the issue:
```python
In [1]: from datasets import load_dataset

In [2]: ds = load_dataset("josianem/imdb")

In [2]: ds
Out[2]: 
DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25799
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})
```

Could you please retry to load the dataset? Maybe there was a temporary connection issue to Dropbox.

**Comment by sauravtii** [comment]
I am facing another issue now

```
Traceback (most recent call last):
  File "sample.py", line 4, in <module>
    dataset = load_dataset("josianem/imdb")
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/load.py", line 1112, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 636, in download_and_prepare
    self._download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 738, in _download_and_prepare
    verify_splits(self.info.splits, split_dict)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/info_utils.py", line 74, in verify_splits
    raise NonMatchingSplitsSizesError(str(bad_splits))
datasets.utils.info_utils.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', num_bytes=34501348, num_examples=25799, dataset_name='imdb'), 'recorded': SplitInfo(name='train', num_bytes=0, num_examples=0, dataset_name='imdb')}, {'expected': SplitInfo(name='test', num_bytes=32650697, num_examples=25000, dataset_name='imdb'), 'recorded': SplitInfo(name='test', num_bytes=0, num_examples=0, dataset_name='imdb')}, {'expected': SplitInfo(name='unsupervised', num_bytes=67106814, num_examples=50000, dataset_name='imdb'), 'recorded': SplitInfo(name='unsupervised', num_bytes=0, num_examples=0, dataset_name='imdb')}]
```

This is my code

```
from datasets import load_dataset, load_metric

dataset = load_dataset("josianem/imdb")
```

**Comment by albertvillanova** [comment]
Your connection didn't work and you got an empty dataset (`num_bytes=0, num_examples=0`):
```
datasets.utils.info_utils.NonMatchingSplitsSizesError: 
[
    {
        'expected': SplitInfo(name='train', num_bytes=34501348, num_examples=25799, dataset_name='imdb'), 
        'recorded': SplitInfo(name='train', num_bytes=0, num_examples=0, dataset_name='imdb')
    }, 
    {
        'expected': SplitInfo(name='test', num_bytes=32650697, num_examples=25000, dataset_name='imdb'), 
        'recorded': SplitInfo(name='test', num_bytes=0, num_examples=0, dataset_name='imdb')
    }, 
    {
        'expected': SplitInfo(name='unsupervised', num_bytes=67106814, num_examples=50000, dataset_name='imdb'), 
        'recorded': SplitInfo(name='unsupervised', num_bytes=0, num_examples=0, dataset_name='imdb')
    }
]
```

Could you please try the link in your browser and see if it works? https://www.dropbox.com/s/zts98j4vkqtsns6/aclImdb_v2.tar?dl=1
- If it does not work, you should contact the author of the dataset in their Community tab (https://huggingface.co/datasets/josianem/imdb/discussions) and inform them, so that they can host their data elsewhere, for example on the Hugging Face Hub itself

If the link works, you should try to load the dataset but forcing the re-download of the data files (so that the cache is refreshed with the actual data file), by passing `download_mode="force_redownload"`:
```python
dataset = load_dataset("josianem/imdb", download_mode="force_redownload")
```

**Comment by sauravtii** [comment]
After pasting the link in the browser, it did start the download so it seems that the link is working. But even after including the `download_mode` in my code I am facing the same issue:

Error:
```
Traceback (most recent call last):
  File "sample.py", line 4, in <module>
    dataset = load_dataset("josianem/imdb", download_mode="force_redownload")
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/load.py", line 1112, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 636, in download_and_prepare
    self._download_and_prepare(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/builder.py", line 704, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/saurav/.cache/huggingface/modules/datasets_modules/datasets/imdb/cc6ab4acab2799be15d5d217c24548b856156dafdc850165fdc4f2031f27ff2f/imdb.py", line 79, in _split_generators
    archive = dl_manager.download(_DOWNLOAD_URL)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 196, in download
    downloaded_path_or_paths = map_nested(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 197, in map_nested
    return function(data_struct)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 217, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 289, in cached_path
    output_path = get_from_cache(
  File "/home/saurav/.local/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 606, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://www.dropbox.com/s/zts98j4vkqtsns6/aclImdb_v2.tar?dl=1
```

My code:
```
from datasets import load_dataset, load_metric

dataset = load_dataset("josianem/imdb", download_mode="force_redownload")
```

**Comment by sauravtii** [comment]
That worked!! Thanks @albertvillanova : )

```
Downloading builder script: 100%|███████| 4.20k/4.20k [00:00<00:00, 6.69MB/s]
Downloading metadata: 100%|█████████████| 2.60k/2.60k [00:00<00:00, 3.41MB/s]
Downloading readme: 100%|███████████████| 7.52k/7.52k [00:00<00:00, 12.6MB/s]
Downloading and preparing dataset imdb/plain_text to /home/saurav/.cache/huggingface/datasets/josianem___imdb/plain_text/1.0.0/cc6ab4acab2799be15d5d217c24548b856156dafdc850165fdc4f2031f27ff2f...
Downloading data: 100%|███████████████████| 301M/301M [01:32<00:00, 3.25MB/s]
Dataset imdb downloaded and prepared to /home/saurav/.cache/huggingface/datasets/josianem___imdb/plain_text/1.0.0/cc6ab4acab2799be15d5d217c24548b856156dafdc850165fdc4f2031f27ff2f. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████| 3/3 [00:00<00:00, 794.83it/s]
```

The code I used:
```
from datasets import load_dataset, load_metric

dataset = load_dataset("josianem/imdb", download_mode="force_redownload")

```

But when I remove `download_mode="force_redownload"` I get the same error. Any guess on that?
