### ISSUE TITLE
File not found for audio dataset

### ISSUE THREAD

**Issue by RobertBaruch** [huggingface/datasets#5918]
### Describe the bug

After loading an audio dataset, and looking at a sample entry, the `path` element, which is supposed to be the path to the audio file, doesn't actually exist.

### Steps to reproduce the bug

Run bug.py:

```py
import os.path

from datasets import load_dataset

def run() -> None:
    cv13 = load_dataset(
        "mozilla-foundation/common_voice_13_0",
        "hi",
        split="train",
    )

    print(cv13[0])
    audio_file = cv13[0]["path"]
    if not os.path.exists(audio_file):
        raise ValueError(f'File {audio_file} does not exist.')

if __name__ == "__main__":
    run()
```

The result (on my machine):

```json
{'client_id': '0f018a99663f33afbb7d38aee281fb1afcfd07f9e7acd00383f604e1e17c38d6ed8adf1bd2ccbf927a52c5adefb8ac4b158ce27a7c2ed9581e71202eb302dfb3', 'path': 'C:\\Users\\rober\\.cache\\huggingface\\datasets\\downloads\\extracted\\8d1479bc09b4609bc2675bd02d6869a4d5e09f7e6616f540bd55eacef46c6e2b\\common_voice_hi_26008353.mp3', 'audio': {'path': 'C:\\Users\\rober\\.cache\\huggingface\\datasets\\downloads\\extracted\\8d1479bc09b4609bc2675bd02d6869a4d5e09f7e6616f540bd55eacef46c6e2b\\common_voice_hi_26008353.mp3', 'array': array([ 6.46234854e-26, -1.35709319e-25, -8.07793567e-26, ...,
        1.06425944e-07,  4.46417090e-08,  2.61451660e-09]), 'sampling_rate': 48000}, 'sentence': 'हमने उसका जन्मदिन मनाया।', 'up_votes': 2, 'down_votes': 0, 'age': '', 'gender': '', 'accent': '', 'locale': 'hi', 'segment': '' ', 'variant': ''}
```

```txt
Traceback (most recent call last):
  File "F:\eo-reco\bug.py", line 18, in <module>
    run()
  File "F:\eo-reco\bug.py", line 15, in run
    raise ValueError(f'File {audio_file} does not exist.')
ValueError: File C:\Users\rober\.cache\huggingface\datasets\downloads\extracted\8d1479bc09b4609bc2675bd02d6869a4d5e09f7e6616f540bd55eacef46c6e2b\common_voice_hi_26008353.mp3 does not exist.
```

### Expected behavior

The `path` element points to the correct file, which happens to be:

```
C:\Users\rober\.cache\huggingface\datasets\downloads\extracted\8d1479bc09b4609bc2675bd02d6869a4d5e09f7e6616f540bd55eacef46c6e2b\hi_train_0\common_voice_hi_26008353.mp3
```

That is, there's an extra directory `hi_train_0` that is not in the `path` element.

### Environment info

- `datasets` version: 2.12.0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.11.3
- Huggingface_hub version: 0.14.1
- PyArrow version: 12.0.0
- Pandas version: 2.0.1
-

**Comment by flckv** [comment]
load_dataset () did not work for loading local files either

**Comment by atronchi** [comment]
Running into a similar issue:
```
librispeech_test = load_dataset("librispeech", split="validation.clean")
print(librispeech_test[0])

{'audio': {'path': '/Users/atronchinjames/.cache/huggingface/datasets/downloads/extracted/991033b10b2fdbb4848dd62dc93fd44d7a0231b7b1752465fbc4fcbdb1f81933/2277-149896-0000.flac',
  'array': array([ 0.00186157,  0.0005188 ,  0.00024414, ..., -0.00097656,
         -0.00109863, -0.00146484], shape=(105440,)),
  'sampling_rate': 16000},
 'dataset': 'librispeech',
 'text': "he was in a fevered state of mind owing to the blight his wife's action threatened to cast upon his entire future",
 'id': '2277-149896-0000'}

$ ls /Users/atronchinjames/.cache/huggingface/datasets/downloads/extracted/991033b10b2fdbb4848dd62dc93fd44d7a0231b7b1752465fbc4fcbdb1f81933/2277-149896-0000.flac
ls: /Users/atronchinjames/.cache/huggingface/datasets/downloads/extracted/991033b10b2fdbb4848dd62dc93fd44d7a0231b7b1752465fbc4fcbdb1f81933/2277-149896-0000.flac: No such file or directory

$ find /Users/atronchinjames/.cache/huggingface/datasets/downloads/extracted | grep 2277-149896-0000.flac
/Users/atronchinjames/.cache/huggingface/datasets/downloads/extracted/991033b10b2fdbb4848dd62dc93fd44d7a0231b7b1752465fbc4fcbdb1f81933/LibriSpeech/dev-clean/2277/149896/2277-149896-0000.flac
```

At least the filename is correct so I can scan through the extracted paths to dig it up. 🤷 
* Python 3.10.16 (main, Dec  3 2024, 17:27:57) [Clang 16.0.0 (clang-1600.0.26.4)]
* huggingface-hub==0.36.0
* datasets==3.6.0
* fsspec==2024.12.0
