### ISSUE TITLE
laion-coco download error

### ISSUE THREAD

**Issue by yangyijune** [huggingface/datasets#6058]
### Describe the bug

The full trace:
```
/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/load.py:1744: FutureWarning: 'ignore_verifications' was de
precated in favor of 'verification_mode' in version 2.9.1 and will be removed in 3.0.0.
You can remove this warning by passing 'verification_mode=no_checks' instead.
  warnings.warn(               
Downloading and preparing dataset parquet/laion--laion-coco to /home/bian/.cache/huggingface/datasets/laion___parquet/laion--
laion-coco-cb4205d7f1863066/0.0.0/bcacc8bdaa0614a5d73d0344c813275e590940c6ea8bc569da462847103a1afd...
Downloading data: 100%|█| 1.89G/1.89G [04:57<00:00,           
Downloading data files: 100%|█| 1/1 [04:59<00:00, 2           
Extracting data files: 100%|█| 1/1 [00:00<00:00, 13           
Generating train split: 0 examples [00:00, ? examples/s]<_io.BufferedReader 
name='/home/bian/.cache/huggingface/datasets/downlo           
ads/26d7a016d25bbd9443115cfa3092136e8eb2f1f5bcd4154           
0cb9234572927f04c'>                                           
                                                   Traceback (most recent call last):
  File "/home/bian/data/ZOC/download_laion_coco.py", line 4, in <module>
    dataset = load_dataset("laion/laion-coco", ignore_verifications=True)
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/load.py", line 1791, in load_dataset
    builder_instance.download_and_prepare(                    
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/builder.py", line 891, in download_and_prepare
    self._download_and_prepare(                               
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/builder.py", line 986, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/builder.py", line 1748, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/builder.py", line 1842, in _prepare_split_single
    generator = self._generate_tables(**gen_kwargs)           
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/datasets/packaged_modules/parquet/parquet.py", line 67, in 
_generate_tables                                              
    parquet_file = pq.ParquetFile(f)                          
  File "/home/bian/anaconda3/envs/sd/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 323, in __init__
    self.reader.open(          
  File "pyarrow/_parquet.pyx", line 1227, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file
.
```

I have carefully followed the instructions in  #5264  but still get the same error.

Other helpful information: 

```
ds = load_dataset("parquet", data_files=
    ...: "https://huggingface.co/datasets/laion/l
    ...: aion-coco/resolve/d22869de3ccd39dfec1507
    ...: f7ded32e4a518dad24/part-00000-2256f782-1
    ...: 26f-4dc6-b9c6-e6757637749d-c000.snappy.p
    ...: arquet")
Found cached dataset parquet (/home/bian/.cache/huggingface/datasets/parquet/default-a02eea00aeb08b0e/0.0.0/bb8ccf89d9ee38581ff5e51506d721a9b37f14df8090dc9b2d8fb4a40957833f)
100%|██████████████| 1/1 [00:00<00:00,  4.55it/s]
```

### Steps to reproduce the bug

``` 
from datasets import load_dataset

dataset = load_dataset("laion/laion-coco", ignore_verifications=True/False)
```

### Expected behavior

Properly load Laion-coco dataset

### Environment info

datasets==2.11.0 torch==1.12.1 python 3.10

**Comment by mariosasko** [comment]
This can also mean one of the files was not downloaded correctly.

We log an erroneous file's name before raising the reader's error, so this is how you can find the problematic file. Then, you should delete it and call `load_dataset` again.

(I checked all the uploaded files, and they seem to be valid Parquet files, so I don't think this is a bug on their side)
