### ISSUE TITLE
dataset = load_dataset("Hyperspace-Technologies/scp-wiki-text") not working

### ISSUE THREAD

**Issue by userbox020** [huggingface/datasets#6401]
### Describe the bug

```
(datasets) mruserbox@guru-X99:/media/10TB_HHD/_LLM_DATASETS$ python dataset.py
Downloading readme: 100%|███████████████████████████████████| 360/360 [00:00<00:00, 2.16MB/s]
Downloading data: 100%|█████████████████████████████████| 65.1M/65.1M [00:19<00:00, 3.38MB/s]
Downloading data: 100%|█████████████████████████████████| 6.35k/6.35k [00:00<00:00, 20.7kB/s]
Downloading data: 100%|█████████████████████████████████| 7.29M/7.29M [00:01<00:00, 3.99MB/s]
Downloading data files: 100%|██████████████████████████████████| 3/3 [00:21<00:00,  7.14s/it]
Extracting data files: 100%|█████████████████████████████████| 3/3 [00:00<00:00, 1624.23it/s]
Generating train split: 100%|█████████████| 314294/314294 [00:00<00:00, 668186.58 examples/s]
Generating validation split: 120 examples [00:00, 100422.28 examples/s]
Generating test split: 100%|████████████████| 34922/34922 [00:00<00:00, 754683.41 examples/s]
Traceback (most recent call last):
  File "/media/10TB_HHD/_LLM_DATASETS/dataset.py", line 3, in <module>
    dataset = load_dataset("Hyperspace-Technologies/scp-wiki-text")
  File "/home/mruserbox/miniconda3/envs/datasets/lib/python3.10/site-packages/datasets/load.py", line 2153, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/mruserbox/miniconda3/envs/datasets/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/home/mruserbox/miniconda3/envs/datasets/lib/python3.10/site-packages/datasets/builder.py", line 1067, in _download_and_prepare
    verify_splits(self.info.splits, split_dict)
  File "/home/mruserbox/miniconda3/envs/datasets/lib/python3.10/site-packages/datasets/utils/info_utils.py", line 93, in verify_splits
    raise UnexpectedSplits(str(set(recorded_splits) - set(expected_splits)))
datasets.utils.info_utils.UnexpectedSplits: {'validation'}
```

### Steps to reproduce the bug

Name:
`dataset.py`

Code:
```
from datasets import load_dataset
dataset = load_dataset("Hyperspace-Technologies/scp-wiki-text")
```

### Expected behavior

Run without errors

### Environment info

```
name: datasets
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.14.6
      - dill==0.3.7
      - filelock==3.13.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - huggingface-hub==0.19.0
      - idna==3.4
      - multidict==6.0.4
      - multiprocess==0.70.15
      - numpy==1.26.1
      - openai==0.27.8
      - packaging==23.2
      - pandas==2.1.3
      - pip==23.3.1
      - platformdirs==4.0.0
      - pyarrow==14.0.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - six==1.16.0
      - tomli==2.0.1
      - tqdm==4.66.1
      - typer==0.9.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - xxhash==3.4.1
      - yarl==1.9.2
prefix: /home/mruserbox/miniconda3/envs/datasets
```

**Comment by VarunNSrivastava** [comment]
Seems like it's a problem with the dataset, since in the [README](https://huggingface.co/datasets/Hyperspace-Technologies/scp-wiki-text/blob/main/README.md) the validation is not specified. Try cloning the dataset, removing the README (or validation split), and loading it locally/

**Comment by userbox020** [comment]
@VarunNSrivastava thanks brother, working beautiful now

```
C:\_Work\_datasets>py dataset.py
Downloading data files: 100%|████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 599.90it/s]
Generating train split: 314294 examples [00:00, 1293222.03 examples/s]
Generating validation split: 120 examples [00:00, 59053.91 examples/s]
Generating test split: 34922 examples [00:00, 1343275.84 examples/s]
```
